services:
  - type: web
    name: smart-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SUPABASE_URL
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        value: ${SUPABASE_KEY}
        